# Generated by Django 5.0.2 on 2024-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_created_at_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsettings',
            name='text_len',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='title_len',
            field=models.IntegerField(default=40),
        ),
    ]
